export interface HomeRoot {
  status: boolean
  message: string
  data: Data
}

export interface Data {
  id: number
  meta_title: string
  meta_description: string
  meta_image: string
  saturn_return_section_title: string
  saturn_return_section_desc: string
  saturn_return_section1_image: string
  saturn_return_section1_title: string
  saturn_return_section2_image: string
  saturn_return_section2_title: string
  saturn_return_section3_image: string
  saturn_return_section3_title: string
  saturn_return_link: string
  saturn_return_link_text: string
  saturn_return_section_status: number
  career_resource_title: string
  career_resource_desc: string
  career_resource_sec_title1: string
  career_resource_sec_image1: string
  career_resource_sec_desc1: string
  career_resource_sec_price1: string
  career_resource_sec_link1: string
  career_resource_sec_link1_text: string
  career_resource_sec_title2: string
  career_resource_sec_image2: string
  career_resource_sec_desc2: string
  career_resource_sec_price2: string
  career_resource_sec_link2: string
  career_resource_sec_link2_text: string
  career_resource_sec_title3: string
  career_resource_sec_image3: string
  career_resource_sec_desc3: string
  career_resource_sec_price3: string
  career_resource_sec_link3: string
  career_resource_sec_link3_text: string
  career_resource_section_status: number
  what_client_say_title1: string
  what_client_say_topic1: string
  what_client_say_description1: string
  what_client_say_name1: string
  what_client_say_location1: string
  what_client_say_image1: string
  what_client_say_title2: string
  what_client_say_topic2: string
  what_client_say_description2: string
  what_client_say_name2: string
  what_client_say_location2: string
  what_client_say_image2: string
  what_client_say_title3: string
  what_client_say_topic3: string
  what_client_say_description3: string
  what_client_say_name3: string
  what_client_say_location3: string
  what_client_say_image3: string
  what_client_say_section_status: number
  reading_with_title: string
  reading_with_desc: string
  reading_with_sec_title: string
  reading_with_sec_desc: string
  reading_with_sec_image: string
  reading_with_sec_link: string
  reading_with_sec_link_text: string
  reading_with_section_status: number
  what_help_section_title: string
  what_help_section1_image: string
  what_help_section1_title: string
  what_help_section1_order: string
  what_help_section2_image: string
  what_help_section2_title: string
  what_help_section2_order: string
  what_help_section3_image: string
  what_help_section3_title: string
  what_help_section3_order: string
  what_help_section_status: number
  birth_chart_report_title: string
  birth_chart_report_desc: string
  birth_chart_report_link: string
  birth_chart_report_link_text: string
  birth_chart_section_status: number
  about_title: string
  about_image: string
  about_desc: string
  about_link: string
  about_link_text: string
  about_section_status: number
  free_gift_title: string
  free_gift_subtitle: string
  free_gift_image: string
  free_gift_desc: string
  free_gift_link: string
  free_gift_link_text: string
  free_gift_section_status: number
  saturn_return_section1_image_path: string
  saturn_return_section2_image_path: string
  saturn_return_section3_image_path: string
  career_resource_section_image1_path: string
  career_resource_section_image2_path: string
  career_resource_section_image3_path: string
  what_client_say_image1_path: string
  what_client_say_image2_path: string
  what_client_say_image3_path: string
  reading_with_section_image_path: string
  what_help_section1_image_path: string
  what_help_section2_image_path: string
  what_help_section3_image_path: string
  about_image_path: string
  free_gift_image_path: string
  homebanner: Homebanner[]
}

export interface Homebanner {
  id: number
  home_cms_id: number
  banner_title: string
  banner_description: string
  banner_link: string
  banner_image: string
  banner_link_text: string
  banner_image_path: string
}